name: Testing Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
 
jobs:
  testing:
    name: Build check

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_dir: [ "java/advanced/BannerRecyclerViewExample", "java/advanced/APIDemo"]

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Set commit range (push to the master branch, e.g. merge)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV
        
      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV
        
      - name: Set changes
        run:  echo "CHANGES=$(git --no-pager diff --name-only $COMMIT_RANGE)" >> $GITHUB_ENV
      
      - name: Build check
        run: echo "BUILD_CHECK=$(grep -E "(${{ matrix.project_dir }}|\.github/workflows/build\.yml)" <<< "$CHANGES")"  >> $GITHUB_ENV
        
      - name: Check changes
        run: echo "Commit range $COMMIT_RANGE, Changes $CHANGES, Build check $BUILD_CHECK"
        
      - name: build
        if: env.BUILD_CHECK != ""
        run: ./{{ matrix.project_dir }}/gradlew build
