name: Testing Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
 
jobs:
  testing:
    name: Build check

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_dir: 
          - "java/advanced/BannerRecyclerViewExample"
          - "java/admob/BannerExample"
          - "java/admob/InterstitialExample"

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Set commit range (push to the master branch, e.g. merge)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: echo "COMMIT_RANGE="${{ github.event.before }}.."" >> $GITHUB_ENV
        
      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo "COMMIT_RANGE="HEAD~.."" >> $GITHUB_ENV
        
      - name: Set changes
        run:  echo "CHANGES=$(git --no-pager diff --name-only $COMMIT_RANGE)" >> $GITHUB_ENV
      
      - name: Build if needed
        if: contains(env.CHANGES, '.github/workflows/build.yml') || contains(env.CHANGES, matrix.project_dir)
        run: |
          echo "Building ${{ matrix.project_dir }} due to changes $CHANGES"
          pushd "${{ matrix.project_dir }}";
          ./gradlew build;
          popd;

