name: Testing Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
 
jobs:
  testing:
    name: Build check

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_dir: [ "java/advanced/BannerRecyclerViewExample", "java/advanced/APIDemo"]

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Set commit range (push to the master branch, e.g. merge)
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: echo ::set-env name=COMMIT_RANGE::${{ github.event.before }}..""
        
      - name: Set commit range (pull request)
        if: github.event_name == 'pull_request'
        run: echo ::set-env name=COMMIT_RANGE::"HEAD~.."
        
      - name: Set changes
        run:  echo ::set-env name=CHANGES=$(git --no-pager diff --name-only ${{ env.COMMIT_RANGE }})
        
      - name: Check changes
        run: echo "Commit range ${{env.COMMIT_RANGE }} Changes ${{ env.CHANGES }}"
        
      - name: build
        run: pushd {{ matrix.project_dir }}; ./gradlew build; popd;
